name: build

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      -
         name: Install dependencies
         run: yarn
      -
         name: build dist
         run: yarn build
         
      - name: Commit files
        run: |
          git add .
          git config --local user.email "su@nn.ci"
          git config --local user.name "Saakura"
          git commit --allow-empty -m "update dist" -a
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      -
        name: Upload artifacts dist
        uses: actions/upload-artifact@v2
        with: 
          name: index
          path: dist/index.html
